# Generated by Django 4.1.4 on 2022-12-29 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('print_name', models.CharField(max_length=120)),
                ('filament_type', models.CharField(max_length=10)),
                ('material_length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)])),
                ('print_time', models.CharField(max_length=30)),
                ('print_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('is_academic', models.BooleanField(default=False)),
                ('print_cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000.0)])),
            ],
            options={
                'ordering': ['print_date'],
            },
        ),
    ]
