# Generated by Django 4.1.4 on 2022-12-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='material_length',
            field=models.FloatField(),
        ),
    ]
