# Generated by Django 4.1.4 on 2022-12-29 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_controller', '0003_alter_student_material_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='print_cost',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
    ]
