# Generated by Django 4.1.4 on 2023-01-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_controller', '0007_alter_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
