# Generated by Django 4.1.4 on 2023-01-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_controller', '0008_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='print_date',
            field=models.DateField(),
        ),
    ]
